"""performer slug

Revision ID: 6d66c7948fab
Revises: 8117a2ce04f7
Create Date: 2026-08-27 19:47:27.922235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d66c7948fab'
down_revision: Union[str, Sequence[str], None] = '8117a2ce04f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performers', sa.Column('slug', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'performers', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'performers', type_='unique')
    op.drop_column('performers', 'slug')
    # ### end Alembic commands ###
