"""books with author and title translations

Revision ID: 73024ff4197c
Revises: 7d7cf73c4c72
Create Date: 2026-08-28 19:05:40.060124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73024ff4197c'
down_revision: Union[str, Sequence[str], None] = '7d7cf73c4c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_latin', sa.Text(), nullable=False),
    sa.Column('author_uk', sa.Text(), nullable=True),
    sa.Column('title_original', sa.Text(), nullable=False),
    sa.Column('lang', sa.Text(), nullable=False),
    sa.Column('isbn', sa.Text(), nullable=True),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('audience', sa.Text(), server_default=sa.text("'adult'"), nullable=False),
    sa.Column('war_related', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("audience IN ('adult','teen','child')", name='books_audience_check'),
    sa.CheckConstraint("lang IN ('uk','en','sv','other')", name='books_lang_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_books_author', 'books', ['author_latin'], unique=False)
    op.create_table('book_translations',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('annotation', sa.Text(), nullable=True),
    sa.CheckConstraint("lang IN ('uk','en','sv')", name='book_translations_lang_check'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'lang')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_translations')
    op.drop_index('idx_books_author', table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
