"""genres

Revision ID: 7d7cf73c4c72
Revises: 6d66c7948fab
Create Date: 2026-08-28 17:59:14.009591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d7cf73c4c72'
down_revision: Union[str, Sequence[str], None] = '6d66c7948fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('genre_translations',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.CheckConstraint("lang IN ('uk','en','sv')", name='genre_translations_lang_check'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('genre_id', 'lang')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre_translations')
    op.drop_table('genres')
    # ### end Alembic commands ###
